version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     environment:
       LC_ALL: C.UTF-8
       LANG: C.UTF-8
     steps:
       - checkout
       - run:
            name: install dependencies
            command: |
                wget https://github.com/ethereum/solidity/releases/download/v0.4.21/solc-static-linux
                sudo mv solc-static-linux /usr/local/bin/solc
                sudo chmod +x /usr/local/bin/solc
                sudo apt-get install -y libgmp3-dev libsecp256k1-0 libsecp256k1-dev
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt

       - run:
           name: compile project
           command: |
               . venv/bin/activate
               populus compile
       - run:
           name: run tests
           command: |
               . venv/bin/activate
               pytest
