version: 2
jobs:
   build:
     docker:
       - image: circleci/node:9.11.1
       - image: trufflesuite/ganache-cli
     environment:
       LC_ALL: C.UTF-8
       LANG: C.UTF-8
     steps:
       - checkout
       - run:
           name: install project
           command: |
               npm install
       - run:
           name: run tests
           command: |
               node_modules/.bin/truffle test
